services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    command: ["serve"]

  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./faiss_index:/app/faiss_index
    depends_on:
      - ollama
    environment:
      PYTHONUNBUFFERED: "1"

    command: ["python3", "main.py"]

volumes:
  ollama_models:
  faiss_index: